# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [4]:
# Import torch
import torch

# Create random tensor
tensor = torch.rand(7 , 7)

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [5]:
# Create another random tensor

tensor_1 = torch.rand(7 , 7)
# Perform matrix multiplication
torch.matmul(tensor , tensor_1)

tensor([[2.4979, 2.3802, 2.3071, 1.0848, 2.7407, 1.6998, 2.9102],
        [3.0442, 2.2958, 2.1586, 1.4777, 2.3949, 2.2471, 2.9975],
        [3.0153, 2.9816, 2.4171, 1.4371, 2.9623, 2.1017, 3.3548],
        [3.4012, 3.1569, 2.6479, 1.5640, 3.0908, 2.3484, 3.5413],
        [2.7192, 2.1077, 2.0569, 1.6907, 2.5419, 2.1048, 2.5002],
        [2.6065, 1.9925, 2.0243, 1.1890, 2.2365, 1.7653, 2.3543],
        [2.4864, 2.6075, 1.9092, 1.4111, 2.5385, 1.7474, 2.5805]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [10]:
# Set manual seed
torch.manual_seed(2)

# Create two random tensors
tensor = torch.rand(7,1)

# Matrix multiply tensors
tensor_1  @ tensor

tensor([[1.9251],
        [1.9806],
        [2.5641],
        [1.9472],
        [2.1453],
        [2.0116],
        [2.8896]])

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [11]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)
torch.cuda.manual_seed(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [23]:
# Set random seed
torch.manual_seed(42)

device = "cuda" if torch.cuda.is_available() else "cpu"
# Check for access to GPU
torch.cuda.is_available()
# Create two random tensors on GPU
tensor = torch.rand(2, 3).to(device)
tensor_2 = torch.rand(2, 3).to(device)
print(f"Device : {device}")
print(tensor)
print(tensor_2)


Device : cuda
tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]], device='cuda:0')
tensor([[0.2566, 0.7936, 0.9408],
        [0.1332, 0.9346, 0.5936]], device='cuda:0')



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [28]:
# Perform matmul on tensor_A and tensor_B
mat_tensors = torch.matmul(tensor , tensor_2.permute(1, 0))

### 8. Find the maximum and minimum values of the output of 7.

In [6]:
# Find max
import torch
torch.manual_seed(42)
tensor_7 = torch.rand(7,7)
torch.max(tensor_7)
# Find min
tensor_7.max()
torch.max(tensor_7)
torch.min(tensor_7)

tensor(0.0062)

### 9. Find the maximum and minimum index values of the output of 7.

In [10]:
# Find arg max
tensor_7.argmax()
torch.argmax(tensor_7)

# Find arg min
torch.argmin(tensor_7)

tensor(29)


### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [18]:
# Set seed

torch.manual_seed(7)
# Create random tensor

tensor = torch.rand(1,1,1,10)
# Remove single dimensions
squeeze_tensor = tensor.squeeze(0)
squeeze_tensor.shape
# Print out tensors and their shapes
print(f"original tensor shape {tensor.shape}")
print(f"Remove one dimention from the tensors shape {squeeze_tensor.shape}")

original tensor shape torch.Size([1, 1, 1, 10])
Remove one dimention from the tensors shape torch.Size([1, 1, 10])
